version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - textbook
  ignore:
  - dependency-name: npm
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
- package-ecosystem: npm
  directory: "/smoke"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - textbook
  labels:
  - smoke
